### ISSUE TITLE
loading macclim on MAC os C

### ISSUE THREAD

**Issue by anquegi** [robert-strandh/McCLIM#86] opened 2016-09-09 10:20 UTC
Loading 

in mhy mac os with El capitan
```

* (lisp-implementation-version)

"1.3.9"
* (lisp-implementation-type)

"SBCL"
* (software-type)

"Darwin"
* (software-version)

"15.6.0"
```

All works well, but I get the problem with loacing mcclim-truetype:

```
.....

[package net.tuxee.vectors].......................
[package net.tuxee.paths-ttf].....................
[package mcclim-truetype]................
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {10028F6AB3}>:


NOTE:
* McCLIM was unable to configure itself automatically using
  fontconfig. Therefore you must configure it manually.


Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Proceed
  1: [RETRY                        ] Retry
                                     completing load for #<SYSTEM "mcclim-fonts/truetype">.
  2: [ACCEPT                       ] Continue, treating
                                     completing load for #<SYSTEM "mcclim-fonts/truetype">
                                     as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5: [ABORT                        ] Give up on "mcclim"
  6:                                 Exit debugger, returning to top level.

((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "mcclim-fonts/truetype">)
0] 0
.........
[package clim-null]...............................
[package com.gigamonkeys.binary-data].............
[package com.gigamonkeys.binar

...
```

it seems a problem with reading the available fonts

```
* (clim-listener:run-listener :new-process t)

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {10028F6AB3}>:
  The value
    NIL
  is not of type
    (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME FILE-STREAM)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CHANGE-FONT-PATH] Retry with alternate truetype font path
  1: [ABORT           ] Exit debugger, returning to top level.

(MERGE-PATHNAMES "DejaVuSans.ttf" NIL 51377928) [tl,external]
0]
```

Thanks for your help, and for mantinign this great library

**Comment by dkochmanski** [comment] 2016-09-09 18:08
Thanks for the report, this is a duplicate of #75 (we're working on that)

**Closed by dkochmanski** 2016-09-09 18:08 UTC
