### ISSUE TITLE
Drawing Test "13) Ink - compose in" fails

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#228] opened 2017-06-04 13:52 UTC
(as do the other compose tests).

Backtrace:

```There is no primary method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)>
when called with arguments
  (#<CLIM-CLX::CLX-MEDIUM {101C9687B3}>
   #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NAMED-COLOR "red"> :MASK #<CLIM-INTERNALS::STANDARD-OPACITY 0.25>>).
BREAK was entered because of *BREAK-ON-SIGNALS* (now rebound to NIL).
   [Condition of type SIMPLE-CONDITION]

Restarts:
 0: [CONTINUE] Return from BREAK.
 1: [REASSIGN] Return from BREAK and assign a new value to *BREAK-ON-SIGNALS*.
 2: [RETRY] Retry calling the generic function.
 3: [ABORT] Return to application command loop
 4: [ABORT] Return to application command loop
 5: [ABORT] abort thread (#<THREAD RUNNING {101A24CEF3}>)

Backtrace:
  0: ((:METHOD SB-PCL::NO-PRIMARY-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)> #<CLIM-CLX::CLX-MEDIUM {101C9687B3}> #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NA..
  1: (SB-PCL::CALL-NO-PRIMARY-METHOD #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)> (#<CLIM-CLX::CLX-MEDIUM {101C9687B3}> #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NAMED-COLO..
  2: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*))
  3: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
  4: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*) {7FFFF4FD457B}> #<SB-THREAD:MUTEX "draw-font" owner: #<SB-THREAD:THREAD RUNNING {101A24CEF3}>> NIL T..
  5: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* (CLIM-CLX::CLX-MEDIUM T T T T T T T T T T)) #<CLIM-CLX::CLX-MEDIUM {101C9687B3}> "Text" 20 180 0 NIL :LEFT :BASELINE #<unused argument> #<unused argument> #<unused arg..
  6: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* :AROUND (CLIM-INTERNALS::TRANSFORM-COORDINATES-MIXIN T T T T T T T T T T)) #<CLIM-CLX::CLX-MEDIUM {101C9687B3}> "Text" 20 180 0 NIL :LEFT :BASELINE 21 180 NIL) [fast-m..
  7: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* :AROUND (CLIM:OUTPUT-RECORDING-STREAM T T T T T T T T T T)) #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::BACKEND-OUTPUT {101C9535D3}> "Text" 20 180 0 NIL :LEFT :B..
 --more--
```

**Comment by gas2serra** [comment] 2017-06-04 14:43
At the moment, clx and clxv3 backends are not able to manage complex inks.

**Comment by gas2serra** [comment] 2017-06-05 08:41
Now, it is a regression.
I did not understand if it is due to a my commit or a your.

```
Recursive lock attempt #<SB-THREAD:MUTEX "draw-font" owner: #<SB-THREAD:THREAD "clim-demo" RUNNING {1003C4B8F3}>>.
   [Condition of type SIMPLE-ERROR]

Backtrace:
  0: (SB-THREAD::%TRY-MUTEX #<unavailable argument> #<unavailable argument>)
  1: (SB-THREAD:GRAB-MUTEX #<SB-THREAD:MUTEX "draw-font" owner: #<SB-THREAD:THREAD "clim-demo" RUNNING {1003C4B8F3}>> :WAITP T :TIMEOUT NIL)
  2: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
  3: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*) {7FFFF5A68FAB}> #<SB-THREAD:MUTEX "draw-font" owner: #<SB-THREAD:THREAD "clim-demo" RUNNING {1003C4B..
  4: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* (CLIM-CLX::CLX-MEDIUM T T T T T T T T T T)) #<CLIM-CLX::CLX-MEDIUM {10025672B3}> "Condition type:" 0 5703/512 0 NIL :LEFT :BASELINE #<unused argument> #<unused argumen..
  5: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* :AROUND (CLIM-INTERNALS::TRANSFORM-COORDINATES-MIXIN T T T T T T T T T T)) #<CLIM-CLX::CLX-MEDIUM {10025672B3}> "Condition type:" 0 5703/512 0 NIL :LEFT :BASELINE 1 57..
  6: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
  7: (CLIM:DRAW-TEXT* #<CLIM-CLX::CLX-MEDIUM {10025672B3}> "Condition type:" 0 5703/512 :TRANSFORMATION #<CLIM-INTERNALS::STANDARD-IDENTITY-TRANSFORMATION 1 0 0 1 0 0> :START 0 :END NIL)
  8: ((:METHOD CLIM-INTERNALS::STREAM-WRITE-OUTPUT :AROUND (CLIM:STANDARD-OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-DEBUGGER-PANE-DUMMY DESKTOP-DEBUGGER::DEBUGGER-PANE {1002552A33}> "Condition type:" N..
  9: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
 10: ((LABELS #:G372 :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX::CLX-MEDIUM {10025672B3}>)
 11: ((:METHOD CLIM:INVOKE-WITH-DRAWING-OPTIONS (CLIM:SHEET T)) #<CLIM-CLX::CLX-DEBUGGER-PANE-DUMMY DESKTOP-DEBUGGER::DEBUGGER-PANE {1002552A33}> #<CLOSURE (FLET #:GCONTINUATION5203 :IN CLIM:REPLAY-OUTPUT-..
 12: ((LABELS #:G5199 :IN CLIM:REPLAY-OUTPUT-RECORD) #<CLIM-CLX::CLX-MEDIUM {10025672B3}>)
 13: ((:METHOD CLIM:REPLAY-OUTPUT-RECORD (CLIM-INTERNALS::STANDARD-TEXT-DISPLAYED-OUTPUT-RECORD T)) #<CLIM-INTERNALS::STANDARD-TEXT-DISPLAYED-OUTPUT-RECORD 0,0 ("Condition type:") {1006277673}> #<CLIM-CLX:..
 14: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
 15: ((LABELS #:G372 :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX::CLX-MEDIUM {10025672B3}>)
 16: ((:METHOD CLIM:INVOKE-WITH-DRAWING-OPTIONS (CLIM:SHEET T)) #<CLIM-CLX::CLX-DEBUGGER-PANE-DUMMY DESKTOP-DEBUGGER::DEBUGGER-PANE {1002552A33}> #<CLOSURE (FLET #:GCONTINUATION2042 :IN CLIM:REPLAY-OUTPUT-..
 17: ((:METHOD CLIM:REPLAY-OUTPUT-RECORD :AROUND (CLIM-INTERNALS::GS-INK-MIXIN T)) #<CLIM-INTERNALS::STANDARD-TEXT-DISPLAYED-OUTPUT-RECORD 0,0 ("Condition type:") {1006277673}> #<CLIM-CLX::CLX-DEBUGGER-PAN..
 18: ((:METHOD CLIM:MAP-OVER-OUTPUT-RECORDS-OVERLAPPING-REGION (T CLIM:STANDARD-SEQUENCE-OUTPUT-RECORD T)) #<STANDARD-GENERIC-FUNCTION CLIM:REPLAY-OUTPUT-RECORD (22)> #<CLIM:STANDARD-CELL-OUTPUT-RECORD X 0..
 19: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLIM-CLX::CLX-MEDIUM {10025672B3}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
```

**Comment by gas2serra** [comment] 2017-06-05 09:35
I was my.

The problem is in this method:
```
(defmethod stream-add-output-record :after ((pane clim-stream-pane) record)
  (unless (region-contains-region-p (sheet-region pane)
                                    (stream-output-history pane))
    (change-space-requirements pane)))
```
The Recursive lock happens only if you are using the clim debugger ;)

The error is:

```
There is no primary method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)>
when called with arguments
  (#<CLIM-CLX::CLX-MEDIUM {100759CF43}>
   #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NAMED-COLOR "red"> :MASK #<CLIM-INTERNALS::STANDARD-OPACITY 0.25>>).
   [Condition of type SB-PCL::NO-PRIMARY-METHOD]
See also:
  Common Lisp Hyperspec, 7.6.6.2 [:section]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [ABORT] Return to application command loop
 2: [ABORT] Return to application command loop
 3: [ABORT] Return to application command loop
 4: [ABORT] abort thread (#<THREAD "clim-demo" RUNNING {100656B8F3}>)

Backtrace:
  0: ((:METHOD SB-PCL::NO-PRIMARY-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)> #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NA..
  1: (SB-PCL::CALL-NO-PRIMARY-METHOD #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)> (#<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NAMED-COLO..
  2: (SB-PCL::CALL-NO-PRIMARY-METHOD #<STANDARD-GENERIC-FUNCTION CLIM-CLX::MEDIUM-GCONTEXT (10)> (#<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLIM-INTERNALS::UNIFORM-COMPOSITUM :INK #<CLIM-INTERNALS::NAMED-COLO..
  3: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*))
  4: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
  5: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*) {7FFFF5A6B01B}> #<SB-THREAD:MUTEX "draw-font" owner: #<SB-THREAD:THREAD "clim-demo" RUNNING {100656B..
  6: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* (CLIM-CLX::CLX-MEDIUM T T T T T T T T T T)) #<CLIM-CLX::CLX-MEDIUM {100759CF43}> "Text" 20 180 0 NIL :LEFT :BASELINE #<unused argument> #<unused argument> #<unused arg..
  7: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* :AROUND (CLIM-INTERNALS::TRANSFORM-COORDINATES-MIXIN T T T T T T T T T T)) #<CLIM-CLX::CLX-MEDIUM {100759CF43}> "Text" 20 180 0 NIL :LEFT :BASELINE 21 180 NIL) [fast-m..
  8: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
  9: ((LABELS #:G372 :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX::CLX-MEDIUM {100759CF43}>)
 10: ((:METHOD CLIM:INVOKE-WITH-DRAWING-OPTIONS (CLIM:SHEET T)) #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::BACKEND-OUTPUT {1009F4CD23}> #<CLOSURE (FLET #:GCONTINUATION2042 :IN CLIM:REPLAY-OUTPUT-REC..
 11: ((:METHOD CLIM:REPLAY-OUTPUT-RECORD :AROUND (CLIM-INTERNALS::GS-INK-MIXIN T)) #<CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD X 19:46 Y 86457/512:93609/512 {1007E32193}> #<CLIM-CLX::CLX-APPLICATION-PANE-DUM..
 12: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
 13: ((LABELS #:G372 :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX::CLX-MEDIUM {100759CF43}>)
 14: ((:METHOD CLIM:INVOKE-WITH-DRAWING-OPTIONS (CLIM:SHEET T)) #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::BACKEND-OUTPUT {1009F4CD23}> #<CLOSURE (FLET #:GCONTINUATION2195 :IN CLIM:REPLAY-OUTPUT-REC..
 15: ((:METHOD CLIM:REPLAY-OUTPUT-RECORD :AROUND (CLIM-INTERNALS::GS-CLIP-MIXIN T)) #<CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD X 19:46 Y 86457/512:93609/512 {1007E32193}> #<CLIM-CLX::CLX-APPLICATION-PANE-DU..
 16: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLIM-CLX::CLX-MEDIUM {100759CF43}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN..
 17: ((LABELS #:G372 :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX::CLX-MEDIUM {100759CF43}>)
 18: ((:METHOD CLIM:INVOKE-WITH-DRAWING-OPTIONS (CLIM:SHEET T)) #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::BACKEND-OUTPUT {1009F4CD23}> #<CLOSURE (FLET #:GCONTINUATION2499 :IN CLIM:REPLAY-OUTPUT-REC..
 19: ((:METHOD CLIM:REPLAY-OUTPUT-RECORD :AROUND (CLIM-INTERNALS::GS-TEXT-STYLE-MIXIN T)) #<CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD X 19:46 Y 86457/512:93609/512 {1007E32193}> #<CLIM-CLX::CLX-APPLICATION-P..
 --more--
```

**Comment by dkochmanski** [comment] 2017-06-09 16:26
fixed by the PR

**Closed by dkochmanski** 2017-06-09 16:26 UTC
