### ISSUE TITLE
Drag and Drop Translator demo gives an error

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#336] opened 2017-10-22 19:46 UTC
When I run the D&D Translator from demodemo, things look OK, but if I try to drag one of the rectangles I get the following error when I drag and then release the mouse:

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::INVOKE-WITH-SHEET-MEDIUM-BOUND (5)>
when called with arguments
  (#<CLOSURE (LABELS #:G5 :IN CLIM-INTERNALS::INVOKE-WITH-IDENTITY-TRANSFORMATION) {7FFFF46C2B0B}>
   NIL
   #<CLIM-CLX::CLX-VIEWPORT-PANE-DUMMY "(Unnamed Pane)" {102E9ACF23}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [ABORT] Return to application command loop
 2: [ABORT] Return to application command loop
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {101EFCFFA3}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::INVOKE-WITH-SHEET-MEDIUM-BOUND (5)> #<CLOSURE (LABELS #:G5 :IN CLIM-INTERNALS::INVOKE-WITH-IDENTITY-TRANSFORMATION) {7FF..
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::INVOKE-WITH-SHEET-MEDIUM-BOUND (5)> (#<CLOSURE (LABELS #:G5 :IN CLIM-INTERNALS::INVOKE-WITH-IDENTITY-TRANSFORMATION) {7FF..
  2: ((:METHOD CLIM-INTERNALS::INVOKE-WITH-IDENTITY-TRANSFORMATION (CLIM:SHEET T)) #<CLIM-CLX::CLX-VIEWPORT-PANE-DUMMY "(Unnamed Pane)" {102E9ACF23}> #<CLOSURE (LABELS #:.CONT.17 :IN CLIM:FRAME-DRAG-AND-DR..
  3: ((:METHOD CLIM:FRAME-DRAG-AND-DROP-FEEDBACK (CLIM:STANDARD-APPLICATION-FRAME T T T T T T T)) #<unused argument> #<CLIM:STANDARD-PRESENTATION 100:150,10:60 CLIM-DEMO::RECT {102EA1AEF3}> #<CLIM-CLX::CLX..
  4: ((FLET "POINTER-MOTION2" :IN CLIM-INTERNALS::FRAME-DRAG-AND-DROP) :EVENT #<CLIM:POINTER-EXIT-EVENT {102F252283}> :WINDOW #<CLIM-CLX::CLX-VIEWPORT-PANE-DUMMY "(Unnamed Pane)" {102E9ACF23}> :X 150 :Y 18..
  5: ((SB-PCL::EMF CLIM-INTERNALS::TRACKING-POINTER-LOOP-STEP) #<unused argument> #<unused argument> #<CLIM-INTERNALS::FRAME-TRACKING-POINTER-STATE {102ED2A4F3}> #<CLIM:POINTER-EXIT-EVENT {102F252283}> 150..
  6: ((FLET CLIM-INTERNALS::DO-TRACKING :IN CLIM-INTERNALS::TRACKING-POINTER-LOOP))
  7: ((:METHOD CLIM-INTERNALS::TRACKING-POINTER-LOOP (CLIM-INTERNALS::TRACKING-POINTER-STATE T T)) #<CLIM-INTERNALS::FRAME-TRACKING-POINTER-STATE {102ED2A4F3}> #<unused argument> #<CLIM-CLX::CLX-APPLICATIO..
  8: ((SB-PCL::EMF CLIM-INTERNALS::TRACKING-POINTER-LOOP) #<unused argument> #<unused argument> #<CLIM-INTERNALS::FRAME-TRACKING-POINTER-STATE {102ED2A4F3}> #<CLIM-DEMO::DRAG-TEST {102E9A3AF3}> #<CLIM-CLX:..
  9: (CLIM-INTERNALS::FRAME-DRAG-AND-DROP CLIM-DEMO::COM-DROP-COLOR #<unused argument> #<CLIM:STANDARD-PRESENTATION 100:150,10:60 CLIM-DEMO::RECT {102EA1AEF3}> (CLIM:COMMAND :COMMAND-TABLE #<CLIM:STANDARD-..
 10: ((:METHOD CLIM:CALL-PRESENTATION-TRANSLATOR (CLIM-INTERNALS::PRESENTATION-TRANSLATOR T T T T T T T)) #<Translator CLIM-DEMO::COM-DROP-COLOR from CLIM-DEMO::RECT to CLIM:COMMAND {103FB0E113}> #<CLIM:ST..
 11: (CLIM:THROW-HIGHLIGHTED-PRESENTATION #<CLIM:STANDARD-PRESENTATION 100:150,10:60 CLIM-DEMO::RECT {102EA1AEF3}> (((CLIM:COMMAND-NAME :COMMAND-TABLE #1=#<CLIM:STANDARD-COMMAND-TABLE CLIM-DEMO::DRAG-TEST ..
 12: ((:METHOD CLIM:STREAM-READ-GESTURE (CLIM:STANDARD-EXTENDED-INPUT-STREAM)) #<CLIM-CLX::CLX-INTERACTOR-PANE-DUMMY CLIM-DEMO::INTERACTOR {102E9A5E43}> :TIMEOUT NIL :PEEK-P NIL :INPUT-WAIT-TEST #<FUNCTION..
 13: ((SB-PCL::EMF CLIM:STREAM-READ-GESTURE) #<unused argument> #<unused argument> #<CLIM-CLX::CLX-INTERACTOR-PANE-DUMMY CLIM-DEMO::INTERACTOR {102E9A5E43}> :TIMEOUT NIL :PEEK-P NIL :INPUT-WAIT-TEST #<FUNC..
 14: ((:METHOD CLIM:STREAM-READ-GESTURE :AROUND (CLIM-INTERNALS::DEAD-KEY-MERGING-MIXIN)) #<CLIM-CLX::CLX-INTERACTOR-PANE-DUMMY CLIM-DEMO::INTERACTOR {102E9A5E43}> :TIMEOUT NIL :INPUT-WAIT-TEST #<FUNCTION ..
 15: ((:METHOD CLIM:STREAM-READ-GESTURE (DREI:DREI-INPUT-EDITING-MIXIN)) #<CLIM:STANDARD-INPUT-EDITING-STREAM {102EA1CA13}> :TIMEOUT NIL :PEEK-P NIL :INPUT-WAIT-TEST #<FUNCTION CLIM-INTERNALS::INPUT-CONTEX..
 16: (CLIM-INTERNALS::READ-COMPLETION-GESTURE #<CLIM:STANDARD-INPUT-EDITING-STREAM {102EA1CA13}> (#\ ) T)
 17: (CLIM:COMPLETE-INPUT #<CLIM:STANDARD-INPUT-EDITING-STREAM {102EA1CA13}> #<CLOSURE (LAMBDA (CLIM-INTERNALS::SO-FAR CLIM-INTERNALS::MODE) :IN CLIM-INTERNALS::%ACCEPT) {102EA2AACB}> :PARTIAL-COMPLETERS (..
 18: ((:METHOD CLIM-INTERNALS::%ACCEPT (CLIM-INTERNALS::|(presentation-type CLIM::COMMAND-NAME)| T T CLIM:TEXTUAL-VIEW)) #<CLIM-INTERNALS::|(presentation-type CLIM::COMMAND-NAME)| {1001F91913}> (CLIM:COMMA..
 19: ((FLET "INPUT-CONT22" :IN CLIM:ACCEPT-1))
 --more--
```

**Comment by dkochmanski** [comment] 2017-10-22 19:50
closing as duplicate of #285

**Closed by dkochmanski** 2017-10-22 19:50 UTC
