### ISSUE TITLE
X11 crash

### ISSUE THREAD

**Issue by TeMPOraL** [robert-strandh/McCLIM#99] opened 2016-10-05 01:50 UTC
- System: `Ubuntu 14.04 LTS`
- uname -a: `Linux Galactica 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
- Lisp: `SBCL 1.3.3`
- McCLIM: `cloned earlier today`

Here's a small piece of code that causes the whole X11 to explode on my machine:

``` lisp
(defun hex->color (r g b)
  (apply #'clim:make-rgb-color (mapcar (lambda (num)
                                         (float (/ num 255)))
                                       (list r g b))))

(defparameter +color-app-background+ (hex->color #xFA #xF8 #xEF))   ;#faf8ef
(defparameter +color-board-background+ (hex->color #xBB #xAD #xA0)) ;#bbada0

(clim:define-application-frame 2048-game
    () ()
    (:menu-bar nil)
    (:panes
     (game-main :application
                :width 800
                :heigh 600
                :background +color-app-background+))
    (:layouts
     (default (clim:vertically () game-main
                          (clim:tabling ()
                            (list (clim:make-pane 'clim:label-pane :text "Red")
                                  (clim:make-pane 'clim:label-pane :text "Green")
                                  (clim:make-pane 'clim:label-pane :text "Blue")) 
                            (list (clim:make-pane 'clim:label-pane :text "Intensity")
                                  (clim:make-pane 'clim:label-pane :text "Hue")
                                  (clim:make-pane 'clim:label-pane :text "Saturation")))) )))

(defun run ()
  (clim:run-frame-top-level (clim:make-application-frame '2048-game)))
```

The code is probably seriously wrong because I've just been playing around with McCLIM for few hours in total, but I don't think that a UI library should be able to trigger a total X11 reboot...

(Note: if it doesn't crash immediately after calling `#'run`, try resizing the window using mouse.)

**Comment by gabriel-laddel** [comment] 2016-10-05 03:28
@robert-strandh @dkochmanski 

SEE? 

Now _PLEASE_ fix (or direct jackdaniel to fix) some of the real issues.

**Comment by gabriel-laddel** [comment] 2016-10-05 03:33
@TeMPOraL Since you're a donor, the easiest thing you can do is stop donating until Robert and Jackdaniel fix the key issues preventing McCLIM from serious usage. See the README: https://github.com/gabriel-laddel/clim

**Comment by dkochmanski** [comment] 2016-10-05 05:02
I can't reproduce your problem (this may be because I have a tiling window manager) - resizing window doesn't trigger it neither or me. Later will check on xfce4.

**Comment by TeMPOraL** [comment] 2016-10-05 09:54
I'm running vanilla Unity on this machine. I'll test it out on another, under a tiling manager, when I get the chance.

**Comment by stacksmith** [comment] 2016-10-05 16:54
I cannot get it to crash - resizing, dragging around, dnd, obscuring, etc.
I am running xubuntu 14.04
uname -a ```Linux eli 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```
```SBCL 1.3.8```
Mcclim: cloned today, dkochmanski's ```font-autoconfigure``` branch.

**Comment by PuercoPop** [comment] 2016-10-05 17:10
I haven't been able to get it crash either, @TeMPOraL have you tried reproducing it under Xephyr so you can still debug after after X11 crashes?

**Comment by TeMPOraL** [comment] 2016-10-06 04:33
@PuercoPop thanks for the suggestion; I'll try reproducing under that.

**Comment by dkochmanski** [comment] 2017-08-18 10:06
closing as non-reproducible.

**Closed by dkochmanski** 2017-08-18 10:06 UTC
