### ISSUE TITLE
Listener "Clear Output History" command fails to reset scrollbars

### ISSUE THREAD

**Issue by abridgewater** [robert-strandh/McCLIM#174] opened 2017-04-26 19:20 UTC
This is probably a matter of not having reset the viewport size when clearing the history.
![listener with cleared output](https://cloud.githubusercontent.com/assets/469380/25452490/bb8bb6f6-2a93-11e7-97a6-24a82a7aa33b.png)

**Comment by gas2serra** [comment] 2017-05-29 07:54
Hi,
do you use the command menu "Listener>Clear Output History" or do you call it in the prompt ",Clear Output History"?

**Comment by abridgewater** [comment] 2017-06-01 14:40
I had been using the command menu, but it turns out that the effect occurs when being invoked via the prompt as well.

**Comment by gas2serra** [comment] 2017-06-01 18:30
The problem is in the function 'fit-pane-to-output'. It never decreases the min-height.

` :min-height (max fit-height min-height)`

@dkochmanski Is it a clim standard function? Do you know why we need it?


```
(defmethod fit-pane-to-output ((stream clim-stream-pane))
  ;; Guard against infinite recursion of size is set to :compute, as
  ;; this could get called from the display function. We'll call
  ;; compose-space here, which will invoke the display function
  ;; again..
  (when (and (sheet-mirror stream)
                     (not (or (eq (pane-user-width stream) :compute)
                                  (eq (pane-user-height stream) :compute))))
    (let* ((output (stream-output-history stream))
           (fit-width  (bounding-rectangle-max-x  output))
           (fit-height (bounding-rectangle-max-y output)))
      (multiple-value-bind (width min-width max-width 
                            height min-height max-height)
          (space-requirement-components (compose-space stream))
	(format *debug-io* "##==> ~A ~A ~A ~%" fit-width fit-height (compose-space stream))
      (change-space-requirements stream
                                 :min-width (max fit-width min-width)
                                 :min-height (max fit-height min-height)
                                 :width (max fit-width width)
                                 :height (max fit-height height)
                                 :max-width max-width
                                 :max-height max-height)))))
```

**Comment by gas2serra** [comment] 2017-06-01 18:57
@dkochmanski  What does ':compute' mean?

**Comment by dkochmanski** [comment] 2017-06-04 08:16
it's a size-spec:
```
CLIM application frames accept the \cl{:foreground}, \cl{:background},
\cl{:text-style}, and layout pane options.  The space requirement options
(\cl{:width}, \cl{:height}, and so forth) can also take a size specification of
\cl{:compute}, which causes CLIM to run the display function for the pane, and
make the pane large enough to hold the output of the display function.
```

**Comment by dkochmanski** [comment] 2017-06-04 08:17
http://bauhh.dyndns.org:8000/clim-spec/29-4.html#_1665 ← here

**Comment by gas2serra** [comment] 2017-06-04 08:30
Ok,
I did not see it.
Thanks.

**Comment by dkochmanski** [comment] 2017-06-12 16:44
fixed in develop. closing it.

**Closed by dkochmanski** 2017-06-12 16:44 UTC
