### ISSUE TITLE
bug: region-contains-position-p ((self standard-rectangle-set)

### ISSUE THREAD

**Issue by gas2serra** [robert-strandh/McCLIM#108] opened 2016-11-05 22:23 UTC
```
(clim:REGION-CONTAINS-POSITION-P
	  (clim:REGION-UNION 
                             (clim:MAKE-RECTANGLE* 0 0 100 100)
			     (clim:MAKE-RECTANGLE* 10 10 110 110))
	  105 105)
-->
nil
```

I think the problem is in the following function:

```
(defmethod region-contains-position-p ((self standard-rectangle-set) x y)
  (block nil
    (map-over-bands (lambda (y1 y2 isum)
                      (when (<= y1 y y2)
                        (when (isum-member x isum)
                          (return t)))
                      (when (> y y2)
                        (return nil)))
                    (standard-rectangle-set-bands self))
    nil))
```
My hypo is that we need to change ` (when (> y y2)` with ` (when (< y y2)`.
I'm not sure because I don't know what "standard-rectangle-set" is. 

Alessandro

**Comment by dkochmanski** [comment] 2016-11-07 11:59
It is a subclass of region-set (apparently mcclim-specific), I think the problem is that second return jumps of the function instead of continuing mapping over band (but skipping the current rectangle)

**Comment by dkochmanski** [comment] 2016-11-10 09:10
Fixed in master branch

**Closed by dkochmanski** 2016-11-10 09:10 UTC
