### ISSUE TITLE
When placing an image in a table cell, remaining cells on the same row becomes aligned to the bottom of the image.

### ISSUE THREAD

**Issue by lokedhs** [robert-strandh/McCLIM#92] opened 2016-09-19 07:18 UTC
The test case below creates a table with one row and two columns. The content of the leftmost cell is a single image (specified using the `:IMAGE-FILENAME`  keyword when creating the frame). The second cell contains a number of rows of text.

When rendering this frame, the baseline of the first row of text is aligned with the bottom of the image. The expected behaviour is that the text in the rightmost column would be aligned to the top of the pane.

**Comment by lokedhs** [comment] 2016-09-19 07:18
```
(defpackage :clim-bugdemo
  (:use :cl)
  (:export #:foo-frame))

(in-package :clim-bugdemo)

(clim:define-application-frame foo-frame ()
  ((image :reader foo-frame/image))
  (:panes (content :application
                   :display-function 'display-content
                   :scroll-bars :vertical))
  (:layouts (default content))
  (:default-initargs :width 800 :height 700))

(defmethod initialize-instance :after ((obj foo-frame) &key image-filename)
  (unless image-filename
    (error "~s not specified when creating frame" :image-filename))
  (setf (slot-value obj 'image)
        (clim:make-pattern-from-bitmap-file image-filename)))

(defun display-content (frame stream)
  (clim:formatting-table (stream)
    (clim:formatting-row (stream)
      (clim:formatting-cell (stream)
        (clim:draw-pattern* stream (foo-frame/image frame) 0 0))
      (clim:formatting-cell (stream)
        (format stream "The baseline of the first line of this text will be aligned with the bottom of the image to the left.")
        (loop
          for i from 0 below 10
          do (format stream "~&~r" i))))))
```

**Comment by dkochmanski** [comment] 2016-09-19 07:29
confirmed on my host

how to run (ensure `image.png` is in place):
```common-lisp
(clim:run-frame-top-level
          (clim:make-application-frame
           'clim-bugdemo:foo-frame
           :image-filename "/tmp/image.png")
```

**Comment by lokedhs** [comment] 2016-09-19 07:58
I just discovered that if you add some text to the stream (any text, as long as it's not just a plain newline), then the alignment will be correct (with the added text on top of the image).

**Comment by gas2serra** [comment] 2016-10-21 20:27
Hi,
by default the y-align is :baseline. I think that the baseline of image is its bottom. 
You can just set :align-y key.
```
(defun display-content (frame stream)
  (clim:formatting-table (stream)
    (clim:formatting-row (stream)
      (clim:formatting-cell (stream)
        (clim:draw-pattern* stream (foo-frame/image frame) 0 0))
      (clim:formatting-cell (stream :align-y :top)    
        (format stream "The baseline of the first line of this text will be aligned with the bottom of the image to the left.")
        (loop
          for i from 0 below 10
	   do (format stream "~&~r" i))))))
```
I don't think it is a bug.

Alessandro

**Comment by gas2serra** [comment] 2016-10-22 20:16
You have the same behavior when you print a big "C".
```
(defun display-content (frame stream)
  (clim:formatting-table (stream)
    (clim:formatting-row (stream)
      (clim:formatting-cell (stream)
        (climi::with-text-size (stream 30)
	       (format stream "C")))
      (clim:formatting-cell (stream :align-y :top)    
        (format stream "The baseline of the first line of this text will be aligned with the bottom of the image to the left.")
        (loop
          for i from 0 below 10
       do (format stream "~&~r" i))))))
```

**Comment by dkochmanski** [comment] 2017-06-12 16:50
closing since it is not a bug.

**Closed by dkochmanski** 2017-06-12 16:50 UTC
Labels: bug
