### ISSUE TITLE
"Tables with borders" demo no longer works as expected

### ISSUE THREAD

**Issue by nsrahmad** [robert-strandh/McCLIM#421] opened 2018-01-01 09:58 UTC
Tested with latest quicklisp dist, McCLIM and clx master, with both CCL 1.11.5 and SBCL 1.4.3.

The error is : 
```lisp
WINDOW-ERROR in current request  Code 3.0 [GetWindowAttributes] ID #x50000DD
   [Condition of type XLIB:WINDOW-ERROR]

Restarts:
 0: [ABORT] Return to application command loop
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT-BREAK] Reset this thread
 4: [ABORT] Kill this thread

Backtrace:
  0: (XLIB::X-ERROR XLIB:WINDOW-ERROR :DISPLAY #<DISPLAY :0 (The X.Org Foundation R11906000)> :ERROR-KEY XLIB:WINDOW-ERROR :ASYNCHRONOUS NIL :CURRENT-SEQUENCE 3532 :RESOURCE-ID 83886301 :MAJOR 3 :MINOR 0 :..
  1: (XLIB:DEFAULT-ERROR-HANDLER #<DISPLAY :0 (The X.Org Foundation R11906000)> XLIB:WINDOW-ERROR :ASYNCHRONOUS NIL :CURRENT-SEQUENCE 3532 :RESOURCE-ID 83886301 :MAJOR 3 :MINOR 0 :SEQUENCE 3532)
  2: (XLIB::REPORT-ERROR #<DISPLAY :0 (The X.Org Foundation R11906000)> 3 XLIB:WINDOW-ERROR :ASYNCHRONOUS NIL :CURRENT-SEQUENCE 3532 :RESOURCE-ID 83886301 :MAJOR 3 :MINOR 0 :SEQUENCE 3532)
  3: (XLIB::READ-REPLY #<DISPLAY :0 (The X.Org Foundation R11906000)> #S(XLIB::PENDING-COMMAND :SEQUENCE 3532 :REPLY-BUFFER NIL :PROCESS ...))
  4: (XLIB::GET-WINDOW-ATTRIBUTES-BUFFER #<WINDOW :0 50000DD>)
  5: (XLIB:WINDOW-EVENT-MASK #<WINDOW :0 50000DD>)
  6: (#<STANDARD-METHOD CLIM:ADOPT-FRAME :AFTER (CLIM-CLX::CLX-FRAME-MANAGER CLIM:APPLICATION-FRAME)> #<CLIM-CLX::CLX-FRAME-MANAGER #x3020047FDE0D> #<CLIM-DEMO::TABLE-DEMO #x302004936A3D>)
  7: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (NIL #<STANDARD-METHOD CLIM:ADOPT-FRAME :AFTER (CLIM-CLX::CLX-FRAME-MANAGER CLIM:APPLICATION-FRAME)> . 17503003209151))
  8: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (NIL (#<STANDARD-METHOD CLIM:ADOPT-FRAME :AFTER (CLIM-CLX::CLX-FRAME-MANAGER CLIM:APPLICATION-FRAME)>) ..) 17503003209151)
  9: (NIL #<Unknown Arguments>)
 10: (#<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)> #<CLIM-DEMO::TABLE-DEMO #x302004936A3D>)
 11: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)> #<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)>) 1750300320919..
 12: (NIL #<Unknown Arguments>)
 13: ((:INTERNAL CLIM-DEMO::MAKE-DEMO-BUTTON) #<CLX-PUSH-BUTTON-PANE-DUMMY "(Unnamed Pane)" #x302004826E9D>)
 14: (CLIM-INTERNALS::INVOKE-CALLBACK #<CLX-PUSH-BUTTON-PANE-DUMMY "(Unnamed Pane)" #x302004826E9D> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CLIM-DEMO::MAKE-DEMO-BUTTON) #x30200482709F>)
 15: (#<STANDARD-METHOD CLIM:HANDLE-EVENT (CLIM:PUSH-BUTTON-PANE CLIM:POINTER-BUTTON-RELEASE-EVENT)> #<CLX-PUSH-BUTTON-PANE-DUMMY "(Unnamed Pane)" #x302004826E9D> #<CLIM:POINTER-BUTTON-RELEASE-EVENT #x3020..
 16: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD CLIM:HANDLE-EVENT (CLIM:PUSH-BUTTON-PANE CLIM:POINTER-BUTTON-RELEASE-EVENT)> . 17503003209241))
 17: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD CLIM:HANDLE-EVENT :AROUND (CLIM:BASIC-GADGET CLIM:DEVICE-EVENT)> ..) 17503003209241)
 18: (NIL #<Unknown Arguments>)
 19: (CLIM-EXTENSIONS:SIMPLE-EVENT-LOOP #<CLIM-DEMO:DEMODEMO #x30200480275D>)
 20: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD CLIM:READ-FRAME-COMMAND (CLIM:APPLICATION-FRAME)> . 17503003209303))
 21: (#<STANDARD-METHOD CLIM:READ-FRAME-COMMAND :AROUND (CLIM:APPLICATION-FRAME)> #<CLIM-DEMO:DEMODEMO #x30200480275D> :STREAM NIL)
 22: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD CLIM:READ-FRAME-COMMAND :AROUND (CLIM:APPLICATION-FRAME)> #<STANDARD-METHOD CLIM:READ-FRAME-COMMAND (CLIM:APPLICATION-FRAME)>) 17503003209303)
 23: (NIL #<Unknown Arguments>)
 24: (CCL::%%CHECK-KEYWORDS #(1 #(:STREAM) #<Combined-Method CLIM:READ-FRAME-COMMAND #x30200491453F>) 17503003209318)
 25: (NIL #<Unknown Arguments>)
 26: (#<STANDARD-METHOD CLIM:DEFAULT-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)> #<CLIM-DEMO:DEMODEMO #x30200480275D> :COMMAND-PARSER CLIM:COMMAND-LINE-COMMAND-PARSER :COMMAND-UNPARSER CLIM:COMMAND-LINE-COMM..
 27: (CCL::%%CHECK-KEYWORDS #(1 #(:PROMPT :PARTIAL-COMMAND-PARSER :COMMAND-UNPARSER :COMMAND-PARSER) #<METHOD-FUNCTION CLIM:DEFAULT-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)>) 17503003209377)
 28: (NIL #<Unknown Arguments>)
 29: (#<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)> #<CLIM-DEMO:DEMODEMO #x30200480275D>)
 30: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)> . 17503003209467))
 31: (#<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)> #<CLIM-DEMO:DEMODEMO #x30200480275D>)
 32: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)> #<STANDARD-METHOD CLIM:RUN-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)>) 1750300320946..
 33: (NIL #<Unknown Arguments>)
 34: (CCL::CALL-CHECK-REGS CLIM-DEMO:DEMODEMO)
 35: (CCL::CHEAP-EVAL (CLIM-DEMO:DEMODEMO))
 36: (SWANK::EVAL-REGION "(clim-demo:demodemo)\n")
 37: ((:INTERNAL SWANK-REPL::REPL-EVAL))
 38: (SWANK-REPL::TRACK-PACKAGE #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x302004802B3F>)
 39: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x302004802BBF>)
 40: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x302004802BFF>)
 41: (SWANK-REPL::REPL-EVAL "(clim-demo:demodemo)\n")
 42: (CCL::CALL-CHECK-REGS SWANK-REPL:LISTENER-EVAL "(clim-demo:demodemo)\n")
 43: (CCL::CHEAP-EVAL (SWANK-REPL:LISTENER-EVAL "(clim-demo:demodemo)\n"))
 44: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(clim-demo:demodemo)\n") "COMMON-LISP-USER" 6)
 45: (SWANK::PROCESS-REQUESTS NIL)
 46: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 47: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 48: (SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK #<Compiled-function SWANK:SWANK-DEBUGGER-HOOK (Non-Global)  #x30200082DABF> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK::HANDLE-REQUESTS) #x3020009669FF>)
 49: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #<SWANK/GRAY::SLIME-INPUT-STREAM #x30200095CBBD>) (*STANDARD-OUTPUT* . #<SWANK/GRAY::SLIME-OUTPUT-STREAM #x30200095CADD>) ..))) #<COMPILED-LEXICAL-CLOSU..
 50: (SWANK::HANDLE-REQUESTS #<MULTITHREADED-CONNECTION #x30200083EB9D> NIL)
 51: (CCL::RUN-PROCESS-INITIAL-FORM #<PROCESS repl-thread(12) [Active] #x30200094BF6D> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x30200094BCFF>))
 52: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) #<PROCESS repl-thread(12) [Active] #x30200094BF6D> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x30200094BCFF>))
 53: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))
```

**Comment by karlosz** [comment] 2018-01-02 07:18
Apparently fixed in SBCL master.

**Comment by karlosz** [comment] 2018-01-02 07:21
Nevermind, there was some other SBCL specific problem fixed.

**Comment by dkochmanski** [comment] 2018-01-20 09:55
This regression is caused by commit 47c847d5665a2a2935ac16645bf29d71761a3305

```
commit 47c847d5665a2a2935ac16645bf29d71761a3305
Author: Daniel Kochmanski <daniel@turtleware.eu>
Date:   Wed Dec 6 07:53:19 2017 +0100

    make-space-requirements: make default w/h = 0 (instead of = 1).
    
    This is important for cases, where we assign all space req components to 0. In
    that case in viewport when we do
    
        (make-space-requirement :max-width chld-max-width :max-height chld-max-height)
    
    where chld-max-width and chld-max-height are both 0, we fail on assertion, that
    width <= max-width.
```

**Comment by dkochmanski** [comment] 2018-01-20 09:58
fixed by 69ab1526ba6796805292bb5be3cdc23d82ba8be4 (simple revert, I  don't remember where did this bogus fix come from, but we have to fix the problem on the caller side if we encounter problem with the assertion encountered in the commit).

**Comment by nsrahmad** [comment] 2018-01-20 16:54
![gifcast_180120221012](https://user-images.githubusercontent.com/10996250/35185788-8ecfda96-fe2f-11e7-8d2c-6974d8ad3849.gif)
Note what happens when I click.
P.S. Ignore the noise at right, I didn't bother to find alternative to gifcast.

**Comment by dkochmanski** [comment] 2018-01-20 16:58
yes, this is caused by fix to this commit (you have even mentioned that it will cause it):
https://github.com/robert-strandh/McCLIM/issues/408

Reverting 5fbe43ad27342916c893c1084e117f2ba6834f69 makes demo work fine but breaks the inspector.

**Closed** 2018-01-21 18:25 UTC
Labels: regression
